# Generated by Django 5.1 on 2024-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
